# Generated by Django 4.2.1 on 2023-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pics")),
                ("desc", models.CharField(max_length=300)),
                ("category", models.CharField(max_length=20)),
                ("link", models.CharField(max_length=50)),
            ],
        ),
    ]
